default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: tester
  password: <%= ENV['TESTER_POSTGRES_PASS'] %>
  database: test_publish_data_vo_development

test:
  <<: *default
  username: tester
  password: <%= ENV['TESTER_POSTGRES_PASS'] %>
  database: test_publish_data_vo_test

production:
  <<: *default
  username: postgres
  password: 
  database: publish_data_vo_production