default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: publish_data_vo_development

test:
  <<: *default
  database: publish_data_vo_test

production:
  <<: *default
  database: publish_data_vo_production
  username: publish_data_vo
  password: <%= ENV['PUBLISH_DATA_VO_DATABASE_PASSWORD'] %>
